apiVersion: v1
kind: Service
metadata:
  name: my-loadbalancer
spec:
  type: ClusterIP
  ports: 
   - port: 80
     targetPort: 80
     protocol: TCP
  selector:
    app: my-deploy
    pod-template-hash: 7d68885db5