apiVersion: v1
kind: Service
metadata:
  name: my-clusterip
spec:
  type: LoadBalancer
  ports: 
   - port: 80
     targetPort: 80
     nodePort: 30008
  selector:
    app: my-deploy
    pod-template-hash: 7d68885db5
