apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  type: NodePort
  selector:
    app: my-deploy
    pod-template-hash: 7d68885db5
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30008
